version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kevin
      POSTGRES_DB: microservice
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nameko:
    build: .
    command: nameko run --config config.yaml user_service
    ports:
      - "8001:8001"
    depends_on:
      - db

volumes:
  postgres-data:
