version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kevin
      POSTGRES_DB: microservice
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabitcontainer
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # Port utilisé par RabbitMQ
      - "15672:15672" # Port utilisé par l'interface web de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persiste les données de RabbitMQ

  nameko:
    build: .
    command: nameko run --config config.yaml user_service
    ports:
      - "8001:8001"
    depends_on:
      - db
      - rabbitmq
    links:
      - "rabbitmq:rabitcontainer"

volumes:
  rabbitmq_data:
  postgres-data:
