version: "3.9"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kevin
      POSTGRES_DB: microservice
    volumes:
      - postgres-data:/var/lib/postgresql/data
  rabbit:
    container_name: rabitcontainer
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672" # Port utilisé par RabbitMQ
      - "15672:15672" # Port utilisé par l'interface web de RabbitMQ
   
   

  nameko:
    build: .
    command: nameko run --config config.yaml user_service
    ports:
      - "8001:8001"
    depends_on:
      - db
      - rabbit
    environment:
        RABBIT_PASSWORD: "guest"
        RABBIT_USER: "guest"
        RABBIT_HOST: "rabbitmq"
        RABBIT_PORT: "5672"
        RABBIT_MANAGEMENT_PORT: "15672"
    links:
      - "rabbit:rabitcontainer"
volumes:
  rabbitmq_data:
  postgres-data:
